<?php

namespace App\Entity;

use App\Repository\LinksRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LinksRepository::class)
 */
class Links
{
    public static $icons = [
        0  => 'fa-network-wired'                        ,
        1  => 'fa-font-awesome'                        ,
        2  => 'fa-google-plus-official'                ,
        3  => 'fa-themeisle'                           ,
        4  => 'fa-yoast'                               ,
        5  => 'fa-first-order'                         ,
        6  => 'fa-pied-piper'                          ,
        7  => 'fa-snapchat-square'                     ,
        8  => 'fa-snapchat-ghost'                      ,
        9  => 'fa-snapchat'                            ,
        10 => 'fa-viadeo-square'                       ,
        11 => 'fa-viadeo'                              ,
        12 => 'fa-low-vision'                          ,
        13 => 'fa-sign-language'                       ,
        14 => 'fa-glide-g'                             ,
        15 => 'fa-glide'                               ,
        16 => 'fa-deaf'                                ,
        17 => 'fa-american-sign-language-interpreting' ,
        18 => 'fa-assistive-listening-systems'         ,
        19 => 'fa-braille'                             ,
        20 => 'fa-volume-control-phone'                ,
        21 => 'fa-audio-description'                   ,
        22 => 'fa-blind'                               ,
        23 => 'fa-question-circle-o'                   ,
        24 => 'fa-wheelchair-alt'                      ,
        25 => 'fa-universal-access'                    ,
        26 => 'fa-envira'                              ,
        27 => 'fa-wpforms'                             ,
        28 => 'fa-wpbeginner'                          ,
        29 => 'fa-gitlab'                              ,
        30 => 'fa-percent'                             ,
        31 => 'fa-bluetooth-b'                         ,
        32 => 'fa-bluetooth'                           ,
        33 => 'fa-hashtag'                             ,
        34 => 'fa-shopping-basket'                     ,
        35 => 'fa-shopping-bag'                        ,
        36 => 'fa-stop-circle-o'                       ,
        37 => 'fa-stop-circle'                         ,
        38 => 'fa-pause-circle-o'                      ,
        39 => 'fa-pause-circle'                        ,
        40 => 'fa-scribd'                              ,
        41 => 'fa-mixcloud'                            ,
        42 => 'fa-product-hunt'                        ,
        43 => 'fa-usb'                                 ,
        44 => 'fa-fort-awesome'                        ,
        45 => 'fa-modx'                                ,
        46 => 'fa-codiepie'                            ,
        47 => 'fa-credit-card-alt'                     ,
        48 => 'fa-edge'                                ,
        49 => 'fa-reddit-alien'                        ,
        50 => 'fa-fonticons'                           ,
        51 => 'fa-black-tie'                           ,
        52 => 'fa-vimeo'                               ,
        53 => 'fa-houzz'                               ,
        54 => 'fa-commenting-o'                        ,
        55 => 'fa-commenting'                          ,
        56 => 'fa-map'                                 ,
        57 => 'fa-map-o'                               ,
        58 => 'fa-map-signs'                           ,
        59 => 'fa-map-pin'                             ,
        60 => 'fa-industry'                            ,
        61 => 'fa-calendar-check-o'                    ,
        62 => 'fa-calendar-times-o'                    ,
        63 => 'fa-calendar-minus-o'                    ,
        64 => 'fa-calendar-plus-o'                     ,
        65 => 'fa-amazon'                              ,
        66 => 'fa-500px'                               ,
        67 => 'fa-contao'                              ,
        68 => 'fa-television'                          ,
        69 => 'fa-internet-explorer'                   ,
        70 => 'fa-opera'                               ,
        71 => 'fa-firefox'                             ,
        72 => 'fa-chrome'                              ,
        73 => 'fa-safari'                              ,
        74 => 'fa-wikipedia-w'                         ,
        75 => 'fa-get-pocket'                          ,
        76 => 'fa-odnoklassniki-square'                ,
        77 => 'fa-odnoklassniki'                       ,
        78 => 'fa-tripadvisor'                         ,
        79 => 'fa-gg-circle'                           ,
        80 => 'fa-gg'                                  ,
        81 => 'fa-creative-commons'                    ,
        82 => 'fa-registered'                          ,
        83 => 'fa-trademark'                           ,
        84 => 'fa-hand-peace-o'                        ,
        85 => 'fa-hand-pointer-o'                      ,
        86 => 'fa-hand-spock-o'                        ,
        87 => 'fa-hand-lizard-o'                       ,
        88 => 'fa-hand-scissors-o'                     ,
        89 => 'fa-hand-paper-o'                        ,
        90 => 'fa-hand-rock-o'                         ,
        91 => 'fa-hourglass'                           ,
        92 => 'fa-hourglass-end'                       ,
        93 => 'fa-hourglass-half'                      ,
        94 => 'fa-hourglass-start'                     ,
        95 => 'fa-hourglass-o'                         ,
        96 => 'fa-balance-scale'                       ,
        97 => 'fa-clone'                               ,
        98 => 'fa-cc-diners-club'                      ,
        99 => 'fa-cc-jcb'                              ,
        100=> 'fa-sticky-note-o'                       ,
        101=> 'fa-sticky-note'                         ,
        102=> 'fa-object-ungroup'                      ,
        103=> 'fa-object-group'                        ,
        104=> 'fa-i-cursor'                            ,
        105=> 'fa-mouse-pointer'                       ,
        106=> 'fa-battery-empty'                       ,
        107=> 'fa-battery-quarter'                     ,
        108=> 'fa-battery-half'                        ,
        109=> 'fa-battery-three-quarters'              ,
        110=> 'fa-battery-full'                        ,
        111=> 'fa-expeditedssl'                        ,
        112=> 'fa-opencart'                            ,
        113=> 'fa-optin-monster'                       ,
        114=> 'fa-y-combinator'                        ,
        115=> 'fa-medium'                              ,
        116=> 'fa-subway'                              ,
        117=> 'fa-train'                               ,
        118=> 'fa-viacoin'                             ,
        119=> 'fa-bed'                                 ,
        120=> 'fa-user-times'                          ,
        121=> 'fa-user-plus'                           ,
        122=> 'fa-server'                              ,
        123=> 'fa-whatsapp'                            ,
        124=> 'fa-pinterest-p'                         ,
        125=> 'fa-facebook-official'                   ,
        126=> 'fa-genderless'                          ,
        127=> 'fa-neuter'                              ,
        128=> 'fa-mars-stroke-h'                       ,
        129=> 'fa-mars-stroke-v'                       ,
        130=> 'fa-mars-stroke'                         ,
        131=> 'fa-venus-mars'                          ,
        132=> 'fa-mars-double'                         ,
        133=> 'fa-venus-double'                        ,
        134=> 'fa-transgender-alt'                     ,
        135=> 'fa-transgender'                         ,
        136=> 'fa-mercury'                             ,
        137=> 'fa-mars'                                ,
        138=> 'fa-venus'                               ,
        139=> 'fa-heartbeat'                           ,
        140=> 'fa-street-view'                         ,
        141=> 'fa-motorcycle'                          ,
        142=> 'fa-user-secret'                         ,
        143=> 'fa-ship'                                ,
        144=> 'fa-diamond'                             ,
        145=> 'fa-cart-arrow-down'                     ,
        146=> 'fa-cart-plus'                           ,
        147=> 'fa-skyatlas'                            ,
        148=> 'fa-simplybuilt'                         ,
        149=> 'fa-shirtsinbulk'                        ,
        150=> 'fa-sellsy'                              ,
        151=> 'fa-leanpub'                             ,
        152=> 'fa-forumbee'                            ,
        153=> 'fa-dashcube'                            ,
        154=> 'fa-connectdevelop'                      ,
        155=> 'fa-buysellads'                          ,
        156=> 'fa-meanpath'                            ,
        157=> 'fa-ils'                                 ,
        158=> 'fa-cc'                                  ,
        159=> 'fa-angellist'                           ,
        160=> 'fa-ioxhost'                             ,
        161=> 'fa-bus'                                 ,
        162=> 'fa-bicycle'                             ,
        163=> 'fa-toggle-on'                           ,
        164=> 'fa-toggle-off'                          ,
        165=> 'fa-lastfm-square'                       ,
        166=> 'fa-lastfm'                              ,
        167=> 'fa-line-chart'                          ,
        168=> 'fa-pie-chart'                           ,
        169=> 'fa-area-chart'                          ,
        170=> 'fa-birthday-cake'                       ,
        171=> 'fa-paint-brush'                         ,
        172=> 'fa-eyedropper'                          ,
        173=> 'fa-at'                                  ,
        174=> 'fa-copyright'                           ,
        175=> 'fa-trash'                               ,
        176=> 'fa-bell-slash-o'                        ,
        177=> 'fa-bell-slash'                          ,
        178=> 'fa-cc-stripe'                           ,
        179=> 'fa-cc-paypal'                           ,
        180=> 'fa-cc-amex'                             ,
        181=> 'fa-cc-discover'                         ,
        182=> 'fa-cc-mastercard'                       ,
        183=> 'fa-cc-visa'                             ,
        184=> 'fa-google-wallet'                       ,
        185=> 'fa-paypal'                              ,
        186=> 'fa-calculator'                          ,
        187=> 'fa-wifi'                                ,
        188=> 'fa-newspaper-o'                         ,
        189=> 'fa-yelp'                                ,
        190=> 'fa-twitch'                              ,
        191=> 'fa-slideshare'                          ,
        192=> 'fa-plug'                                ,
        193=> 'fa-binoculars'                          ,
        194=> 'fa-tty'                                 ,
        195=> 'fa-futbol-o'                            ,
        196=> 'fa-bomb'                                ,
        197=> 'fa-share-alt-square'                    ,
        198=> 'fa-share-alt'                           ,
        199=> 'fa-sliders'                             ,
        200=> 'fa-paragraph'                           ,
        201=> 'fa-header'                              ,
        202=> 'fa-circle-thin'                         ,
        203=> 'fa-history'                             ,
        204=> 'fa-paper-plane-o'                       ,
        205=> 'fa-paper-plane'                         ,
        206=> 'fa-weixin'                              ,
        207=> 'fa-qq'                                  ,
        208=> 'fa-tencent-weibo'                       ,
        209=> 'fa-hacker-news'                         ,
        210=> 'fa-git'                                 ,
        211=> 'fa-git-square'                          ,
        212=> 'fa-empire'                              ,
        213=> 'fa-rebel'                               ,
        214=> 'fa-circle-o-notch'                      ,
        215=> 'fa-life-ring'                           ,
        216=> 'fa-jsfiddle'                            ,
        217=> 'fa-codepen'                             ,
        218=> 'fa-vine'                                ,
        219=> 'fa-file-code-o'                         ,
        220=> 'fa-file-video-o'                        ,
        221=> 'fa-file-audio-o'                        ,
        222=> 'fa-file-archive-o'                      ,
        223=> 'fa-file-image-o'                        ,
        224=> 'fa-file-powerpoint-o'                   ,
        225=> 'fa-file-excel-o'                        ,
        226=> 'fa-file-word-o'                         ,
        227=> 'fa-file-pdf-o'                          ,
        228=> 'fa-database'                            ,
        229=> 'fa-soundcloud'                          ,
        230=> 'fa-deviantart'                          ,
        231=> 'fa-spotify'                             ,
        232=> 'fa-tree'                                ,
        233=> 'fa-taxi'                                ,
        234=> 'fa-car'                                 ,
        235=> 'fa-recycle'                             ,
        236=> 'fa-steam-square'                        ,
        237=> 'fa-steam'                               ,
        238=> 'fa-behance-square'                      ,
        239=> 'fa-behance'                             ,
        240=> 'fa-cubes'                               ,
        241=> 'fa-cube'                                ,
        242=> 'fa-spoon'                               ,
        243=> 'fa-paw'                                 ,
        244=> 'fa-child'                               ,
        245=> 'fa-building'                            ,
        246=> 'fa-fax'                                 ,
        247=> 'fa-language'                            ,
        248=> 'fa-joomla'                              ,
        249=> 'fa-drupal'                              ,
        250=> 'fa-pied-piper-alt'                      ,
        251=> 'fa-pied-piper-pp'                       ,
        252=> 'fa-digg'                                ,
        253=> 'fa-delicious'                           ,
        254=> 'fa-stumbleupon'                         ,
        255=> 'fa-stumbleupon-circle'                  ,
        256=> 'fa-reddit-square'                       ,
        257=> 'fa-reddit'                              ,
        258=> 'fa-google'                              ,
        259=> 'fa-yahoo'                               ,
        260=> 'fa-graduation-cap'                      ,
        261=> 'fa-university'                          ,
        262=> 'fa-openid'                              ,
        263=> 'fa-wordpress'                           ,
        264=> 'fa-envelope-square'                     ,
        265=> 'fa-slack'                               ,
        266=> 'fa-space-shuttle'                       ,
        267=> 'fa-plus-square-o'                       ,
        268=> 'fa-try'                                 ,
        269=> 'fa-vimeo-square'                        ,
        270=> 'fa-wheelchair'                          ,
        271=> 'fa-dot-circle-o'                        ,
        272=> 'fa-caret-square-o-left'                 ,
        273=> 'fa-arrow-circle-o-left'                 ,
        274=> 'fa-arrow-circle-o-right'                ,
        275=> 'fa-stack-exchange'                      ,
        276=> 'fa-pagelines'                           ,
        277=> 'fa-renren'                              ,
        278=> 'fa-weibo'                               ,
        279=> 'fa-vk'                                  ,
        280=> 'fa-bug'                                 ,
        281=> 'fa-archive'                             ,
        282=> 'fa-moon-o'                              ,
        283=> 'fa-sun-o'                               ,
        284=> 'fa-gratipay'                            ,
        285=> 'fa-male'                                ,
        286=> 'fa-female'                              ,
        287=> 'fa-trello'                              ,
        288=> 'fa-foursquare'                          ,
        289=> 'fa-skype'                               ,
        290=> 'fa-dribbble'                            ,
        291=> 'fa-linux'                               ,
        292=> 'fa-android'                             ,
        293=> 'fa-windows'                             ,
        294=> 'fa-apple'                               ,
        295=> 'fa-long-arrow-right'                    ,
        296=> 'fa-long-arrow-left'                     ,
        297=> 'fa-long-arrow-up'                       ,
        298=> 'fa-long-arrow-down'                     ,
        299=> 'fa-tumblr-square'                       ,
        300=> 'fa-tumblr'                              ,
        301=> 'fa-bitbucket-square'                    ,
        302=> 'fa-bitbucket'                           ,
        303=> 'fa-adn'                                 ,
        304=> 'fa-flickr'                              ,
        305=> 'fa-instagram'                           ,
        306=> 'fa-stack-overflow'                      ,
        307=> 'fa-dropbox'                             ,
        308=> 'fa-youtube-play'                        ,
        309=> 'fa-xing-square'                         ,
        310=> 'fa-xing'                                ,
        311=> 'fa-youtube'                             ,
        312=> 'fa-youtube-square'                      ,
        313=> 'fa-thumbs-down'                         ,
        314=> 'fa-thumbs-up'                           ,
        315=> 'fa-sort-numeric-desc'                   ,
        316=> 'fa-sort-numeric-asc'                    ,
        317=> 'fa-sort-amount-desc'                    ,
        318=> 'fa-sort-amount-asc'                     ,
        319=> 'fa-sort-alpha-desc'                     ,
        320=> 'fa-sort-alpha-asc'                      ,
        321=> 'fa-file-text'                           ,
        322=> 'fa-file'                                ,
        323=> 'fa-btc'                                 ,
        324=> 'fa-krw'                                 ,
        325=> 'fa-rub'                                 ,
        326=> 'fa-jpy'                                 ,
        327=> 'fa-inr'                                 ,
        328=> 'fa-usd'                                 ,
        329=> 'fa-gbp'                                 ,
        330=> 'fa-eur'                                 ,
        331=> 'fa-caret-square-o-right'                ,
        332=> 'fa-caret-square-o-up'                   ,
        333=> 'fa-caret-square-o-down'                 ,
        334=> 'fa-compass'                             ,
        335=> 'fa-share-square'                        ,
        336=> 'fa-external-link-square'                ,
        337=> 'fa-pencil-square'                       ,
        338=> 'fa-check-square'                        ,
        339=> 'fa-level-down'                          ,
        340=> 'fa-level-up'                            ,
        341=> 'fa-minus-square-o'                      ,
        342=> 'fa-minus-square'                        ,
        343=> 'fa-ticket'                              ,
        344=> 'fa-play-circle'                         ,
        345=> 'fa-rss-square'                          ,
        346=> 'fa-ellipsis-v'                          ,
        347=> 'fa-ellipsis-h'                          ,
        348=> 'fa-bullseye'                            ,
        349=> 'fa-unlock-alt'                          ,
        350=> 'fa-anchor'                              ,
        351=> 'fa-css3'                                ,
        352=> 'fa-html5'                               ,
        353=> 'fa-chevron-circle-down'                 ,
        354=> 'fa-chevron-circle-up'                   ,
        355=> 'fa-chevron-circle-right'                ,
        356=> 'fa-chevron-circle-left'                 ,
        357=> 'fa-maxcdn'                              ,
        358=> 'fa-rocket'                              ,
        359=> 'fa-fire-extinguisher'                   ,
        360=> 'fa-calendar-o'                          ,
        361=> 'fa-shield'                              ,
        362=> 'fa-microphone-slash'                    ,
        363=> 'fa-microphone'                          ,
        364=> 'fa-puzzle-piece'                        ,
        365=> 'fa-eraser'                              ,
        366=> 'fa-subscript'                           ,
        367=> 'fa-superscript'                         ,
        368=> 'fa-exclamation'                         ,
        369=> 'fa-info'                                ,
        370=> 'fa-question'                            ,
        371=> 'fa-chain-broken'                        ,
        372=> 'fa-code-fork'                           ,
        373=> 'fa-crop'                                ,
        374=> 'fa-location-arrow'                      ,
        375=> 'fa-star-half-o'                         ,
        376=> 'fa-reply-all'                           ,
        377=> 'fa-code'                                ,
        378=> 'fa-terminal'                            ,
        379=> 'fa-flag-checkered'                      ,
        380=> 'fa-flag-o'                              ,
        381=> 'fa-keyboard-o'                          ,
        382=> 'fa-gamepad'                             ,
        383=> 'fa-meh-o'                               ,
        384=> 'fa-frown-o'                             ,
        385=> 'fa-smile-o'                             ,
        386=> 'fa-folder-open-o'                       ,
        387=> 'fa-folder-o'                            ,
        388=> 'fa-github-alt'                          ,
        389=> 'fa-reply'                               ,
        390=> 'fa-circle'                              ,
        391=> 'fa-spinner'                             ,
        392=> 'fa-quote-right'                         ,
        393=> 'fa-quote-left'                          ,
        394=> 'fa-circle-o'                            ,
        395=> 'fa-mobile'                              ,
        396=> 'fa-tablet'                              ,
        397=> 'fa-laptop'                              ,
        398=> 'fa-desktop'                             ,
        399=> 'fa-angle-down'                          ,
        400=> 'fa-angle-up'                            ,
        401=> 'fa-angle-right'                         ,
        402=> 'fa-angle-left'                          ,
        403=> 'fa-angle-double-down'                   ,
        404=> 'fa-angle-double-up'                     ,
        405=> 'fa-angle-double-right'                  ,
        406=> 'fa-angle-double-left'                   ,
        407=> 'fa-plus-square'                         ,
        408=> 'fa-h-square'                            ,
        409=> 'fa-beer'                                ,
        410=> 'fa-fighter-jet'                         ,
        411=> 'fa-medkit'                              ,
        412=> 'fa-ambulance'                           ,
        413=> 'fa-hospital-o'                          ,
        414=> 'fa-building-o'                          ,
        415=> 'fa-file-text-o'                         ,
        416=> 'fa-cutlery'                             ,
        417=> 'fa-coffee'                              ,
        418=> 'fa-bell-o'                              ,
        419=> 'fa-suitcase'                            ,
        420=> 'fa-stethoscope'                         ,
        421=> 'fa-user-md'                             ,
        422=> 'fa-cloud-upload'                        ,
        423=> 'fa-cloud-download'                      ,
        424=> 'fa-exchange'                            ,
        425=> 'fa-lightbulb-o'                         ,
        426=> 'fa-clipboard'                           ,
        427=> 'fa-umbrella'                            ,
        428=> 'fa-sitemap'                             ,
        429=> 'fa-bolt'                                ,
        430=> 'fa-comments-o'                          ,
        431=> 'fa-comment-o'                           ,
        432=> 'fa-tachometer'                          ,
        433=> 'fa-gavel'                               ,
        434=> 'fa-undo'                                ,
        435=> 'fa-linkedin'                            ,
        436=> 'fa-envelope'                            ,
        437=> 'fa-sort-asc'                            ,
        438=> 'fa-sort-desc'                           ,
        439=> 'fa-sort'                                ,
        440=> 'fa-columns'                             ,
        441=> 'fa-caret-right'                         ,
        442=> 'fa-caret-left'                          ,
        443=> 'fa-caret-up'                            ,
        444=> 'fa-caret-down'                          ,
        445=> 'fa-money'                               ,
        446=> 'fa-google-plus'                         ,
        447=> 'fa-google-plus-square'                  ,
        448=> 'fa-pinterest-square'                    ,
        449=> 'fa-pinterest'                           ,
        450=> 'fa-truck'                               ,
        451=> 'fa-magic'                               ,
        452=> 'fa-table'                               ,
        453=> 'fa-underline'                           ,
        454=> 'fa-strikethrough'                       ,
        455=> 'fa-list-ol'                             ,
        456=> 'fa-list-ul'                             ,
        457=> 'fa-bars'                                ,
        458=> 'fa-square'                              ,
        459=> 'fa-floppy-o'                            ,
        460=> 'fa-paperclip'                           ,
        461=> 'fa-files-o'                             ,
        462=> 'fa-scissors'                            ,
        463=> 'fa-flask'                               ,
        464=> 'fa-cloud'                               ,
        465=> 'fa-link'                                ,
        466=> 'fa-users'                               ,
        467=> 'fa-arrows-alt'                          ,
        468=> 'fa-briefcase'                           ,
        469=> 'fa-filter'                              ,
        470=> 'fa-tasks'                               ,
        471=> 'fa-wrench'                              ,
        472=> 'fa-globe'                               ,
        473=> 'fa-arrow-circle-down'                   ,
        474=> 'fa-arrow-circle-up'                     ,
        475=> 'fa-arrow-circle-right'                  ,
        476=> 'fa-arrow-circle-left'                   ,
        477=> 'fa-hand-o-down'                         ,
        478=> 'fa-hand-o-up'                           ,
        479=> 'fa-hand-o-left'                         ,
        480=> 'fa-hand-o-right'                        ,
        481=> 'fa-certificate'                         ,
        482=> 'fa-bell'                                ,
        483=> 'fa-bullhorn'                            ,
        484=> 'fa-hdd-o'                               ,
        485=> 'fa-rss'                                 ,
        486=> 'fa-credit-card'                         ,
        487=> 'fa-unlock'                              ,
        488=> 'fa-github'                              ,
        489=> 'fa-facebook'                            ,
        490=> 'fa-twitter'                             ,
        491=> 'fa-phone-square'                        ,
        492=> 'fa-bookmark-o'                          ,
        493=> 'fa-square-o'                            ,
        494=> 'fa-phone'                               ,
        495=> 'fa-lemon-o'                             ,
        496=> 'fa-upload'                              ,
        497=> 'fa-github-square'                       ,
        498=> 'fa-trophy'                              ,
        499=> 'fa-sign-in'                             ,
        500=> 'fa-external-link'                       ,
        501=> 'fa-thumb-tack'                          ,
        502=> 'fa-linkedin-square'                     ,
        503=> 'fa-sign-out'                            ,
        504=> 'fa-heart-o'                             ,
        505=> 'fa-star-half'                           ,
        506=> 'fa-thumbs-o-down'                       ,
        507=> 'fa-thumbs-o-up'                         ,
        508=> 'fa-comments'                            ,
        509=> 'fa-cogs'                                ,
        510=> 'fa-key'                                 ,
        511=> 'fa-camera-retro'                        ,
        512=> 'fa-facebook-square'                     ,
        513=> 'fa-twitter-square'                      ,
        514=> 'fa-bar-chart'                           ,
        515=> 'fa-arrows-h'                            ,
        516=> 'fa-arrows-v'                            ,
        517=> 'fa-folder-open'                         ,
        518=> 'fa-folder'                              ,
        519=> 'fa-shopping-cart'                       ,
        520=> 'fa-retweet'                             ,
        521=> 'fa-chevron-down'                        ,
        522=> 'fa-chevron-up'                          ,
        523=> 'fa-magnet'                              ,
        524=> 'fa-comment'                             ,
        525=> 'fa-random'                              ,
        526=> 'fa-calendar'                            ,
        527=> 'fa-plane'                               ,
        528=> 'fa-exclamation-triangle'                ,
        529=> 'fa-eye-slash'                           ,
        530=> 'fa-eye'                                 ,
        531=> 'fa-fire'                                ,
        532=> 'fa-leaf'                                ,
        533=> 'fa-gift'                                ,
        534=> 'fa-exclamation-circle'                  ,
        535=> 'fa-asterisk'                            ,
        536=> 'fa-minus'                               ,
        537=> 'fa-plus'                                ,
        538=> 'fa-compress'                            ,
        539=> 'fa-expand'                              ,
        540=> 'fa-share'                               ,
        541=> 'fa-arrow-down'                          ,
        542=> 'fa-arrow-up'                            ,
        543=> 'fa-arrow-right'                         ,
        544=> 'fa-arrow-left'                          ,
        545=> 'fa-ban'                                 ,
        546=> 'fa-check-circle-o'                      ,
        547=> 'fa-times-circle-o'                      ,
        548=> 'fa-crosshairs'                          ,
        549=> 'fa-info-circle'                         ,
        550=> 'fa-question-circle'                     ,
        551=> 'fa-check-circle'                        ,
        552=> 'fa-times-circle'                        ,
        553=> 'fa-minus-circle'                        ,
        554=> 'fa-plus-circle'                         ,
        555=> 'fa-chevron-right'                       ,
        556=> 'fa-chevron-left'                        ,
        557=> 'fa-eject'                               ,
        558=> 'fa-step-forward'                        ,
        559=> 'fa-fast-forward'                        ,
        560=> 'fa-forward'                             ,
        561=> 'fa-stop'                                ,
        562=> 'fa-pause'                               ,
        563=> 'fa-play'                                ,
        564=> 'fa-backward'                            ,
        565=> 'fa-fast-backward'                       ,
        566=> 'fa-step-backward'                       ,
        567=> 'fa-arrows'                              ,
        568=> 'fa-check-square-o'                      ,
        569=> 'fa-share-square-o'                      ,
        570=> 'fa-pencil-square-o'                     ,
        571=> 'fa-tint'                                ,
        572=> 'fa-adjust'                              ,
        573=> 'fa-map-marker'                          ,
        574=> 'fa-pencil'                              ,
        575=> 'fa-picture-o'                           ,
        576=> 'fa-video-camera'                        ,
        577=> 'fa-indent'                              ,
        578=> 'fa-outdent'                             ,
        579=> 'fa-list'                                ,
        580=> 'fa-align-justify'                       ,
        581=> 'fa-align-right'                         ,
        582=> 'fa-align-center'                        ,
        583=> 'fa-align-left'                          ,
        584=> 'fa-text-width'                          ,
        585=> 'fa-text-height'                         ,
        586=> 'fa-italic'                              ,
        587=> 'fa-bold'                                ,
        588=> 'fa-font'                                ,
        589=> 'fa-camera'                              ,
        590=> 'fa-print'                               ,
        591=> 'fa-bookmark'                            ,
        592=> 'fa-book'                                ,
        593=> 'fa-tags'                                ,
        594=> 'fa-tag'                                 ,
        595=> 'fa-barcode'                             ,
        596=> 'fa-qrcode'                              ,
        597=> 'fa-volume-up'                           ,
        598=> 'fa-volume-down'                         ,
        599=> 'fa-volume-off'                          ,
        600=> 'fa-headphones'                          ,
        601=> 'fa-flag'                                ,
        602=> 'fa-lock'                                ,
        603=> 'fa-list-alt'                            ,
        604=> 'fa-refresh'                             ,
        605=> 'fa-repeat'                              ,
        606=> 'fa-play-circle-o'                       ,
        607=> 'fa-inbox'                               ,
        608=> 'fa-arrow-circle-o-up'                   ,
        609=> 'fa-arrow-circle-o-down'                 ,
        610=> 'fa-download'                            ,
        611=> 'fa-road'                                ,
        612=> 'fa-clock-o'                             ,
        613=> 'fa-file-o'                              ,
        614=> 'fa-home'                                ,
        615=> 'fa-trash-o'                             ,
        616=> 'fa-cog'                                 ,
        617=> 'fa-signal'                              ,
        618=> 'fa-power-off'                           ,
        619=> 'fa-search-minus'                        ,
        620=> 'fa-search-plus'                         ,
        621=> 'fa-times'                               ,
        622=> 'fa-check'                               ,
        623=> 'fa-th-list'                             ,
        624=> 'fa-th'                                  ,
        625=> 'fa-th-large'                            ,
        626=> 'fa-film'                                ,
        627=> 'fa-user'                                ,
        628=> 'fa-star-o'                              ,
        629=> 'fa-star'                                ,
        630=> 'fa-heart'                               ,
        631=> 'fa-envelope-o'                          ,
        632=> 'fa-search'                              ,
        633=> 'fa-music'                               ,
        634=> 'fa-glass'                               ,
        635=> "fa-network-wired"                       ,
        636=> "fa-shield-virus"                        ,
        637=> "fa-fill-drip"                           ,
        638=> "fa-door-open"                            
    ]; 
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $href;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $icon;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enable;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHref(): ?string
    {
        return $this->href;
    }

    public function setHref(string $href): self
    {
        $this->href = $href;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(?string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(?string $icon): self
    {
        $this->icon = $icon;

        return $this;
    }

    public function getEnable(): ?bool
    {
        return $this->enable;
    }

    public function setEnable(bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }
}
